### ISSUE TITLE
No way to bookmark a team on the main page

### ISSUE THREAD

**Issue by sahuguet** [cornelltech/studio-reports#13]
There is no <a> tag to reference a team inside the page using #team-name.
Page: http://buildboard-10044.cornelltech.io/directory.html

I want to be able to do http://buildboard-10044.cornelltech.io/directory.html#uber-blah
where we use the repo name for the team.

**Comment by elanid** [comment]
Added. https://github.com/cornelltech/studio-reports/commit/11019c5f81c9deb1ef8f7fd3586d62bb41e75d94
