### ISSUE TITLE
Make it a 2 step process: get the data THEN apply template

### ISSUE THREAD

**Issue by foundry-admin** [cornelltech/studio-reports#3]
If we want to work on the template and test, we need to re-fetch the data every time.
This is time consuming and might be bad if there is some throttling.

1. fetch the data from github
- data from YAML and store it as JSON on disk
- assets
2. apply the template based on the JSON

**Comment by elanid** [comment]
Is there a reason to store as JSON rather than just as YAML files?

**Comment by foundry-admin** [comment]
YAML is fine.

**Comment by elanid** [comment]
Done, as of https://github.com/cornelltech/studio-reports/commit/6809f5270ee2284fb0edeaf94f4b5970b98987
