### ISSUE TITLE
use gflags for main command-line tool

### ISSUE THREAD

**Issue by foundry-admin** [cornelltech/studio-reports#4]
- to fetch the data
- to generate from scratch
- to generate based on local data
- other stuff

**Comment by elanid** [comment]
In a familiar Google story, gflags is deprecated and points to Abseil as the new hotness: https://github.com/abseil/abseil-py

Abseil seems like it will probably work, but is not yet documented in python, which is an extremely irritating oversight.

**Comment by elanid** [comment]
Of course, this deprecation looks like a reasonably recent phenom. https://github.com/google/python-gflags/issues/39

**Comment by elanid** [comment]
Helpfully, their open source page still suggests using gflags! https://opensource.google.com/projects/python-gflags

**Comment by elanid** [comment]
Using native python argparse instead.

https://github.com/cornelltech/studio-reports/commit/2178bf35410ba8ab3f26f072a98d24510650a3a6
https://github.com/cornelltech/studio-reports/commit/623458a4b6bd86bb7b8a49927246d1346c09a62b
