### ISSUE TITLE
Improvement for current page

### ISSUE THREAD

**Issue by foundry-admin** [cornelltech/studio-reports#6]
**Table of contents**
- [ ] add company name
- [ ] add team name if any
- [ ] display status (e.g. assignment submitted)
- [ ] add more info about section, e.g. am vs pm, topic of the section, e.g. health

**List of projects**
- [ ] remove numbers (use ul vs ol)
- [ ] use small-caps for the How-Might-We part
- [ ] use zippy for everything under HMW
- [ ] for each item, add link to go back to ToC
- [ ] truncate product narrative if > N words

**Comment by elanid** [comment]
What is zippy?

**Comment by foundry-admin** [comment]
This is a way to expand/collapse content.
See http://jsfiddle.net/7BLCY/1/ .
There might be other jQuery library for that.

**Comment by elanid** [comment]
I'm closing this as we've instead moved to a completely different design.
